dockCapacity: 40
carArrivalIntervalMs: 600  
ferries:
  - id: 1
    capacity: 12
    maxWaitSeconds: 20
  - id: 2
    capacity: 15
    maxWaitSeconds: 20
  - id: 3
    capacity: 12
    maxWaitSeconds: 25
  - id: 4
    capacity: 12
    maxWaitSeconds: 25
  - id: 5
    capacity: 12
    maxWaitSeconds: 25
  - id: 6
    capacity: 12
    maxWaitSeconds: 25
