dockCapacity: 40
carArrivalIntervalMs: 600  # średni odstęp między autami (ms)
simulationTimeSeconds: 120 # auto‑stop po 2 minutach
ferries:
  - id: 1
    capacity: 12
    maxWaitSeconds: 20
  - id: 2
    capacity: 15
    maxWaitSeconds: 20
  - id: 3
    capacity: 12
    maxWaitSeconds: 25
  - id: 4
    capacity: 12
    maxWaitSeconds: 25
  - id: 5
    capacity: 12
    maxWaitSeconds: 25
  - id: 6
    capacity: 12
    maxWaitSeconds: 25
